// src/app/layout.js
import Hero from "./components/Hero";
import "./styles/globals.css";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        {/* ⭐ Global container wrapper */}
        <div className="container mx-auto px-4">
            {/* <Hero /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
